x-common-config: &common-config
  restart: always
  networks:
    - app-network
  env_file: .env

services:
  backend-dev:
    <<: *common-config
    networks:
      app-network:
        aliases: [ "backend" ]
    build:
      context: ./backend
    profiles: [ "dev" ]
    environment:
      - DB_HOST=${DB_HOST:-db}
    volumes:
      - ./backend:/app
    command: [ "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]
    depends_on:
      db:
        condition: service_healthy

  backend-prod:
    <<: *common-config
    networks:
      app-network:
        aliases: [ "backend" ]
    build: ./backend
    profiles: [ "prod" ]
    environment:
      - DB_HOST=${DB_HOST:-db}
    depends_on:
      db:
        condition: service_healthy

  frontend-dev:
    <<: *common-config
    networks:
      app-network:
        aliases: [ "frontend" ]
    build:
      context: ./frontend
      target: deps
      args: &fe-args
        ENV: ${ENV:-development}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-/api}
        NEXT_PUBLIC_TELEGRAM_BOT_USERNAME: ${NEXT_PUBLIC_TELEGRAM_BOT_USERNAME}
    profiles: [ "dev" ]
    environment:
      <<: *fe-args
      WATCHPACK_POLLING: "true"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend-dev
    command: npm run dev

  frontend-prod:
    <<: *common-config
    networks:
      app-network:
        aliases: [ "frontend" ]
    build:
      context: ./frontend
      args:
        <<: *fe-args
        ENV: ${ENV:-production}
    profiles: [ "prod" ]
    environment:
      <<: *fe-args
      ENV: ${ENV:-production}
    depends_on:
      - backend-prod

  db:
    <<: *common-config
    image: postgres:17-alpine
    profiles: [ "dev" ]
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
      POSTGRES_DB: ${DB_NAME:-split_the_bill_db}
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    <<: *common-config
    image: nginx:latest
    profiles: [ "dev", "prod" ]
    volumes:
      - ./nginx/nginx-${ENV:-production}.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "${NGINX_PORT:-80}:80"
    depends_on:
      backend-dev: { condition: service_started, required: false }
      frontend-dev: { condition: service_started, required: false }
      backend-prod: { condition: service_started, required: false }
      frontend-prod: { condition: service_started, required: false }

  cloudflared:
    <<: *common-config
    image: cloudflare/cloudflared:latest
    profiles: [ "prod" ]
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run
    depends_on:
      - nginx

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
